# Generated by Django 2.0.3 on 2018-06-05 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='The name of the announcer', max_length=50)),
                ('Phone', models.CharField(help_text='Phone number of the announcer', max_length=50)),
                ('Email', models.CharField(help_text='Email of the announcer', max_length=50)),
                ('Category', models.CharField(choices=[('lost', 'lost'), ('found', 'found'), ('on_sale', 'on_sale'), ('event', 'event'), ('announcement', 'announcement')], default='announcement', help_text='The category of the announcement', max_length=20)),
                ('Title', models.TextField(help_text='The title of the announcement')),
                ('Announcement', models.TextField(help_text='The announcement (description of the announcement')),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Type', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', help_text='The type of the announcement. This is whether it is rejected, approved, or pending', max_length=20)),
                ('Icon', models.FileField(upload_to='uploads/announcement-icon')),
            ],
        ),
    ]
