# Generated by Django 2.0.3 on 2018-06-08 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tangaza', '0002_auto_20180605_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Announcement',
            field=models.TextField(help_text='The announcement (description of the announcement)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Category',
            field=models.CharField(choices=[('on_sale', 'on_sale'), ('lost', 'lost'), ('found', 'found'), ('advertisement', 'advertisement'), ('job', 'job'), ('event', 'event'), ('announcement', 'announcement')], default='announcement', help_text='The category of the announcement', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
